send_light_mode:
  name: Nature Remo Light Mode
  description: 指定したライトエンティティに対してボタン名で操作します / Send command to the selected light using button name.
  fields:
    entity_id:
      name: エンティティ / Entity
      required: true
      example: light.nature_remo_light_abcdef
      selector:
        entity:
          domain: light
    mode:
      name: 操作モード / Mode
      description: "実行したい操作モードを選択または入力してください（例: on, night） / Select or input the desired mode (e.g., on, night)"
      required: true
      example: night
      selector:
        select:
          options:
            - 'on'
            - 'on-100'
            - 'on-favorite'
            - 'night'
            - 'bright-up'
            - 'bright-down'
            - 'colortemp-up'
            - 'colortemp-down'
          custom_value: true
